name: Build

on:
  pull_request:
    branches:
      - compile
    paths:
      - '**.c'
      - '**.h'

env:
  REPO: 'compile'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        emacs-version:
          - 28.1
          - snapshot
    steps:
    - uses: actions/checkout@v2
    - name: Set git config
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
  
    - name: Commit
      continue-on-error: true
      run: |
        git pull
        git add .
        git commit -m "Update modules ${{ matrix.targets }}"
    - name: Push
      uses: ad-m/github-push-action@master
      with:
        repository: ${{ env.REPO }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: compile
        retry: 7