name: CMake

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ "main", "develop" ]
    paths: [ "**.c", "**.h" ]

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory.
      run: cmake -B ${{github.workspace}}/build -DCMAKE_C_FLAGS='-O3 -march=native'

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build