name: Test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: ["main", "develop"]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        emacs-version:
          - 28.1
          - snapshot
    steps:
      - uses: actions/checkout@v2

      - uses: dangduc/setup-emacs@master
        with:
          version: ${{ matrix.emacs-version }}

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - uses: emacs-eask/setup-eask@master
        with:
          version: 'snapshot'

      - name: Print emacs version
        run: |
          emacs --version

      - run: echo "$HOME/.cask/bin" >> $GITHUB_PATH
      - run: make compile
      - run: make lint
      - run: make test